12-installation

diff --git a/12-installation b/12-installation
--- a/12-installation
+++ b/12-installation
@@ -4,6 +4,18 @@ USERID=$(id -u)
 
 if [ USERID -ne 0 ]; then
 
-echo "ERROR : Please run the installation with root preveleges"
+echo "ERROR : Please run the installation with root priveleges"
 
 fi
+
+dnf install mysql -y
+
+if [ $? -ne 0 ] then
+
+echo "Installation is failure"
+
+else
+
+echo "I stallation is success"
+
+if
